# Generated by Django 3.0.4 on 2020-03-21 01:05

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mobilpay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentresponse',
            name='r',
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registered on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentresponse',
            name='action',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentresponse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registered on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentresponse',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentresponse',
            name='error_message',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentresponse',
            name='error_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='last_name',
            field=models.CharField(max_length=254, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='order_id',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, unique=True, verbose_name='Order ID'),
        ),
    ]
