# Generated by Django 3.0.4 on 2020-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilpay', '0002_auto_20200321_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
