# Generated by Django 3.0.4 on 2020-03-15 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_auto_20200315_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngoneed',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='hub.NGO'),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='hub.NGO'),
        ),
    ]
