# Generated by Django 3.0.4 on 2020-03-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_auto_20200316_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngohelper',
            name='read',
            field=models.BooleanField(blank=True, null=True, verbose_name='Read on'),
        ),
    ]
