# Generated by Django 3.0.4 on 2020-03-17 19:28

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0008_ngohelper_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterNGORequest",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("name", models.CharField(max_length=254, verbose_name="Name")),
                ("coverage", models.CharField(max_length=254, verbose_name="Coverage")),
                ("email", models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email")),
                ("contact_name", models.CharField(max_length=254, verbose_name="Contact person's name")),
                ("contact_phone", models.CharField(max_length=15, verbose_name="Contact person's phone")),
                ("has_netopia_contract", models.BooleanField(default=False, verbose_name="Has contract with Netopia")),
                (
                    "social_link",
                    models.CharField(blank=True, max_length=512, null=True, verbose_name="Link to website or Facebook"),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Organization's short description - max 500 chars.",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={"ordering": ("-modified", "-created"), "get_latest_by": "modified", "abstract": False,},
        ),
    ]
