# Generated by Django 3.0.4 on 2020-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0009_registerngorequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerngorequest",
            name="coverage",
            field=models.CharField(
                help_text="Country or county/city selection", max_length=254, verbose_name="Coverage"
            ),
        ),
    ]
