# Generated by Django 3.0.4 on 2020-03-17 18:48

from django.db import migrations


def upper_county(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    PersonalRequest = apps.get_model("hub", "PersonalRequest")

    for ngo in PersonalRequest.objects.all():
        ngo.county = ngo.county.upper()
        ngo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_auto_20200317_1833'),
    ]

    operations = [
        migrations.RunPython(upper_county)
    ]
