# Generated by Django 3.0.4 on 2020-03-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0010_auto_20200317_1931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerngorequest",
            name="description",
            field=models.TextField(
                help_text="Organization's short description - max 500 chars.",
                max_length=500,
                verbose_name="Description",
            ),
        ),
    ]
