# Generated by Django 3.0.4 on 2020-03-17 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0011_auto_20200317_1938"),
        ("hub", "0012_auto_20200317_1956"),
    ]

    operations = []
