# Generated by Django 3.0.4 on 2020-03-17 23:02

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_merge_20200317_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ngo',
            options={'verbose_name': 'NGO', 'verbose_name_plural': 'NGOs'},
        ),
        migrations.AlterModelOptions(
            name='ngohelper',
            options={'verbose_name': 'NGO Helpers', 'verbose_name_plural': 'NGO Helper'},
        ),
        migrations.AlterModelOptions(
            name='ngoneed',
            options={'verbose_name': 'NGO need', 'verbose_name_plural': 'NGO needs'},
        ),
        migrations.AlterField(
            model_name='ngo',
            name='county',
            field=models.CharField(choices=[('ALBA', 'ALBA'), ('ARGES', 'ARGES'), ('ARAD', 'ARAD'), ('BACAU', 'BACAU'), ('BIHOR', 'BIHOR'), ('BISTRITA-NASAUD', 'BISTRITA-NASAUD'), ('BRAILA', 'BRAILA'), ('BRASOV', 'BRASOV'), ('BOTOSANI', 'BOTOSANI'), ('BUCURESTI', 'BUCURESTI'), ('BUZAU', 'BUZAU'), ('CLUJ', 'CLUJ'), ('CALARASI', 'CALARASI'), ('CARAS-SEVERIN', 'CARAS-SEVERIN'), ('CONSTANTA', 'CONSTANTA'), ('COVASNA', 'COVASNA'), ('DAMBOVITA', 'DAMBOVITA'), ('DOLJ', 'DOLJ'), ('GORJ', 'GORJ'), ('GALATI', 'GALATI'), ('GIURGIU', 'GIURGIU'), ('HUNEDOARA', 'HUNEDOARA'), ('HARGHITA', 'HARGHITA'), ('IALOMITA', 'IALOMITA'), ('IASI', 'IASI'), ('ILFOV', 'ILFOV'), ('MEHEDINTI', 'MEHEDINTI'), ('MARAMURES', 'MARAMURES'), ('MURES', 'MURES'), ('NEAMT', 'NEAMT'), ('OLT', 'OLT'), ('PRAHOVA', 'PRAHOVA'), ('SIBIU', 'SIBIU'), ('SALAJ', 'SALAJ'), ('SATU-MARE', 'SATU-MARE'), ('SECTOR 1', 'SECTOR 1'), ('SECTOR 2', 'SECTOR 2'), ('SECTOR 3', 'SECTOR 3'), ('SECTOR 4', 'SECTOR 4'), ('SECTOR 5', 'SECTOR 5'), ('SECTOR 6', 'SECTOR 6'), ('SUCEAVA', 'SUCEAVA'), ('TULCEA', 'TULCEA'), ('TIMIS', 'TIMIS'), ('TELEORMAN', 'TELEORMAN'), ('VALCEA', 'VALCEA'), ('VRANCEA', 'VRANCEA'), ('VASLUI', 'VASLUI')], max_length=50, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='ngohelper',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read on'),
        ),
        migrations.AlterField(
            model_name='ngoneed',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='hub.NGO', verbose_name='NGO'),
        ),
        migrations.AlterField(
            model_name='personalrequest',
            name='county',
            field=models.CharField(choices=[('ALBA', 'ALBA'), ('ARGES', 'ARGES'), ('ARAD', 'ARAD'), ('BACAU', 'BACAU'), ('BIHOR', 'BIHOR'), ('BISTRITA-NASAUD', 'BISTRITA-NASAUD'), ('BRAILA', 'BRAILA'), ('BRASOV', 'BRASOV'), ('BOTOSANI', 'BOTOSANI'), ('BUCURESTI', 'BUCURESTI'), ('BUZAU', 'BUZAU'), ('CLUJ', 'CLUJ'), ('CALARASI', 'CALARASI'), ('CARAS-SEVERIN', 'CARAS-SEVERIN'), ('CONSTANTA', 'CONSTANTA'), ('COVASNA', 'COVASNA'), ('DAMBOVITA', 'DAMBOVITA'), ('DOLJ', 'DOLJ'), ('GORJ', 'GORJ'), ('GALATI', 'GALATI'), ('GIURGIU', 'GIURGIU'), ('HUNEDOARA', 'HUNEDOARA'), ('HARGHITA', 'HARGHITA'), ('IALOMITA', 'IALOMITA'), ('IASI', 'IASI'), ('ILFOV', 'ILFOV'), ('MEHEDINTI', 'MEHEDINTI'), ('MARAMURES', 'MARAMURES'), ('MURES', 'MURES'), ('NEAMT', 'NEAMT'), ('OLT', 'OLT'), ('PRAHOVA', 'PRAHOVA'), ('SIBIU', 'SIBIU'), ('SALAJ', 'SALAJ'), ('SATU-MARE', 'SATU-MARE'), ('SECTOR 1', 'SECTOR 1'), ('SECTOR 2', 'SECTOR 2'), ('SECTOR 3', 'SECTOR 3'), ('SECTOR 4', 'SECTOR 4'), ('SECTOR 5', 'SECTOR 5'), ('SECTOR 6', 'SECTOR 6'), ('SUCEAVA', 'SUCEAVA'), ('TULCEA', 'TULCEA'), ('TIMIS', 'TIMIS'), ('TELEORMAN', 'TELEORMAN'), ('VALCEA', 'VALCEA'), ('VRANCEA', 'VRANCEA'), ('VASLUI', 'VASLUI')], max_length=50, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='ngoneed',
            name='resource_tags',
            field=models.ManyToManyField(related_name='needs', to='hub.ResourceTag'),
        ),
    ]
