# Generated by Django 3.0.4 on 2020-03-17 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_auto_20200317_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoneed',
            name='closed_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Closed on'),
        ),
    ]
