# Generated by Django 3.0.4 on 2020-03-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0015_ngoneed_closed_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerngorequest",
            name="active",
            field=models.BooleanField(default=False, verbose_name="Active"),
        ),
        migrations.AddField(
            model_name="registerngorequest",
            name="resolved_on",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Resolved on"),
        ),
        migrations.AlterField(
            model_name="ngoneed",
            name="resource_tags",
            field=models.ManyToManyField(blank=True, related_name="needs", to="hub.ResourceTag"),
        ),
    ]
