# Generated by Django 3.0.4 on 2020-03-18 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_auto_20200318_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerngorequest',
            name='registered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registered on'),
            preserve_default=False,
        ),
    ]
