# Generated by Django 3.0.4 on 2020-03-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_auto_20200320_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='mobilpay_icc',
            field=models.CharField(blank=True, help_text='XXXX-XXXX-XXXX-XXXX-XXXX', max_length=24, null=True, verbose_name='mobilpay Merchant identifier code'),
        ),
    ]
