# Generated by Django 3.0.4 on 2020-03-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0020_auto_20200320_2353"),
    ]

    operations = [
        migrations.AddField(
            model_name="ngoneed",
            name="city",
            field=models.CharField(default="Timisoara", max_length=100, verbose_name="City"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ngoneed",
            name="county",
            field=models.CharField(
                choices=[
                    ("ALBA", "ALBA"),
                    ("ARGES", "ARGES"),
                    ("ARAD", "ARAD"),
                    ("BACAU", "BACAU"),
                    ("BIHOR", "BIHOR"),
                    ("BISTRITA-NASAUD", "BISTRITA-NASAUD"),
                    ("BRAILA", "BRAILA"),
                    ("BRASOV", "BRASOV"),
                    ("BOTOSANI", "BOTOSANI"),
                    ("BUCURESTI", "BUCURESTI"),
                    ("BUZAU", "BUZAU"),
                    ("CLUJ", "CLUJ"),
                    ("CALARASI", "CALARASI"),
                    ("CARAS-SEVERIN", "CARAS-SEVERIN"),
                    ("CONSTANTA", "CONSTANTA"),
                    ("COVASNA", "COVASNA"),
                    ("DAMBOVITA", "DAMBOVITA"),
                    ("DOLJ", "DOLJ"),
                    ("GORJ", "GORJ"),
                    ("GALATI", "GALATI"),
                    ("GIURGIU", "GIURGIU"),
                    ("HUNEDOARA", "HUNEDOARA"),
                    ("HARGHITA", "HARGHITA"),
                    ("IALOMITA", "IALOMITA"),
                    ("IASI", "IASI"),
                    ("ILFOV", "ILFOV"),
                    ("MEHEDINTI", "MEHEDINTI"),
                    ("MARAMURES", "MARAMURES"),
                    ("MURES", "MURES"),
                    ("NEAMT", "NEAMT"),
                    ("OLT", "OLT"),
                    ("PRAHOVA", "PRAHOVA"),
                    ("SIBIU", "SIBIU"),
                    ("SALAJ", "SALAJ"),
                    ("SATU-MARE", "SATU-MARE"),
                    ("SECTOR 1", "SECTOR 1"),
                    ("SECTOR 2", "SECTOR 2"),
                    ("SECTOR 3", "SECTOR 3"),
                    ("SECTOR 4", "SECTOR 4"),
                    ("SECTOR 5", "SECTOR 5"),
                    ("SECTOR 6", "SECTOR 6"),
                    ("SUCEAVA", "SUCEAVA"),
                    ("TULCEA", "TULCEA"),
                    ("TIMIS", "TIMIS"),
                    ("TELEORMAN", "TELEORMAN"),
                    ("VALCEA", "VALCEA"),
                    ("VRANCEA", "VRANCEA"),
                    ("VASLUI", "VASLUI"),
                ],
                default="TIMIS",
                max_length=50,
                verbose_name="County",
            ),
            preserve_default=False,
        ),
    ]
