# Generated by Django 3.0.4 on 2020-03-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0021_auto_20200321_1255"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingRegisterNGORequest",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("hub.registerngorequest",),
        ),
        migrations.AddField(
            model_name="registerngorequest",
            name="dsu_approved",
            field=models.BooleanField(default=False, verbose_name="DSU Approved"),
        ),
        migrations.AddField(
            model_name="registerngorequest",
            name="ffc_approved",
            field=models.BooleanField(default=False, verbose_name="FFC Approved"),
        ),
    ]
