# Generated by Django 3.0.4 on 2020-03-22 13:22

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0022_auto_20200321_0531"),
    ]

    operations = [TrigramExtension(), UnaccentExtension()]
