# Generated by Django 3.0.4 on 2020-03-22 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0023_auto_20200322_1322"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TEXT SEARCH CONFIGURATION romanian_unaccent( COPY = romanian );
            ALTER TEXT SEARCH CONFIGURATION romanian_unaccent
            ALTER MAPPING FOR hword, hword_part, word
            WITH unaccent, romanian_stem;
            """
        )
    ]
