# Generated by Django 3.0.4 on 2020-03-21 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0026_auto_20200321_1526"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registerngorequestvote",
            name="motivation",
            field=models.TextField(
                blank=True, help_text="Motivate your decision", max_length=500, null=True, verbose_name="Motvation"
            ),
        ),
        migrations.AlterField(
            model_name="registerngorequestvote",
            name="ngo_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="hub.RegisterNGORequest"
            ),
        ),
    ]
