# Generated by Django 3.0.4 on 2020-03-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hub", "0027_auto_20200321_1734"),
    ]

    operations = [
        migrations.AddField(
            model_name="registerngorequestvote",
            name="date",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registerngorequestvote",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
