# Generated by Django 3.0.4 on 2020-03-22 15:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0028_auto_20200321_1817"),
    ]

    operations = [
        migrations.CreateModel(
            name="NGOReportItem",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("date", models.DateTimeField(verbose_name="Date")),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("file", models.FileField(blank=True, null=True, upload_to="", verbose_name="Receipt")),
                ("amount", models.FloatField(verbose_name="Amount spent (RON)")),
                (
                    "ngo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="report_items", to="hub.NGO"
                    ),
                ),
            ],
            options={"verbose_name": "NGO report item", "verbose_name_plural": "NGO report items",},
        ),
    ]
