# Generated by Django 3.0.4 on 2020-03-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0034_auto_20200326_0201"),
    ]

    operations = [
        migrations.CreateModel(
            name="NGOAccount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "currency",
                    models.CharField(
                        choices=[("RON", "RON"), ("EUR", "EUR"), ("USD", "USD")],
                        default="RON",
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                ("iban", models.CharField(max_length=40)),
                ("bank", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="ngo",
            name="accepts_mobilpay",
            field=models.BooleanField(default=False, verbose_name="Accepts mobilpay"),
        ),
        migrations.AddField(
            model_name="ngo",
            name="accepts_transfer",
            field=models.BooleanField(default=False, verbose_name="Accepts transfers"),
        ),
        migrations.AddField(
            model_name="ngo", name="cif", field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ngo", name="cui", field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(model_name="ngo", name="donations_description", field=models.TextField(null=True),),
        migrations.AlterField(
            model_name="registerngorequest",
            name="avatar",
            field=models.ImageField(
                help_text="Image should be 500x500px", max_length=300, upload_to="", verbose_name="Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="registerngorequest",
            name="resource_types",
            field=models.TextField(
                help_text="The types of resources you anticipate you will need.",
                max_length=500,
                verbose_name="Resource tags",
            ),
        ),
        migrations.AddField(
            model_name="ngo", name="ibans", field=models.ManyToManyField(null=True, to="hub.NGOAccount"),
        ),
    ]
