# Generated by Django 3.0.4 on 2020-03-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0036_ngo_contact_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="ngo", name="ibans",),
        migrations.AddField(
            model_name="ngoaccount",
            name="ngo",
            field=models.FileField(default="", upload_to="", verbose_name="NGO"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ngo",
            name="cif",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="CIF"),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="cui",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="CUI"),
        ),
    ]
