# Generated by Django 3.0.4 on 2020-03-28 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0037_auto_20200328_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngoaccount",
            name="ngo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="hub.NGO"),
        ),
    ]
