# Generated by Django 3.0.4 on 2020-03-30 21:51

from django.db import migrations, models
import django.db.models.deletion
import hub.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0038_auto_20200328_1401"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ngo",
            name="avatar",
            field=models.ImageField(
                max_length=300, storage=hub.storage_backends.PublicMediaStorage(), upload_to="", verbose_name="Avatar"
            ),
        ),
        migrations.AlterField(
            model_name="ngo", name="donations_description", field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="last_balance_sheet",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                storage=hub.storage_backends.PrivateMediaStorage(),
                upload_to="",
                verbose_name="First page of last balance sheet",
            ),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="mobilpay_private_key",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                storage=hub.storage_backends.PrivateMediaStorage(),
                upload_to="",
                verbose_name="mobilpay Private key",
            ),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="mobilpay_public_key",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                storage=hub.storage_backends.PrivateMediaStorage(),
                upload_to="",
                verbose_name="mobilpay Public key",
            ),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="statute",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                storage=hub.storage_backends.PrivateMediaStorage(),
                upload_to="",
                verbose_name="NGO Statute",
            ),
        ),
        migrations.AlterField(
            model_name="ngoaccount",
            name="ngo",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="accounts", to="hub.NGO"),
        ),
    ]
