# Generated by Django 3.0.4 on 2020-04-04 06:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0040_auto_20200331_0856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourcetag",
            name="name",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid tag consisting of letters, numbers, hyphens or spaces",
                        regex="^[-a-zA-Z0-9\\s,]+$",
                    )
                ],
                verbose_name="Name",
            ),
        ),
    ]
