# Generated by Django 3.0.4 on 2020-04-04 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0041_auto_20200402_1818'),
        ('hub', '0041_auto_20200404_0650'),
    ]

    operations = [
    ]
