# Generated by Django 3.0.4 on 2020-04-04 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0043_auto_20200404_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^(\\+4|)?(07[0-8]{1}[0-9]{1}|02[0-9]{2}|03[0-9]{2}){1}?(\\s|\\.|\\-)?([0-9]{3}(\\s|\\.|\\-|)){2}$')], verbose_name='Phone'),
        ),
    ]
