# Generated by Django 3.0.4 on 2020-04-10 10:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0044_auto_20200409_2029"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ngoreportitem", options={"verbose_name": "Report", "verbose_name_plural": "Report"},
        ),
        migrations.AlterField(
            model_name="ngo",
            name="mobilpay_private_key",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Mobilpay Private key",
            ),
        ),
        migrations.AlterField(
            model_name="ngo",
            name="mobilpay_public_key",
            field=models.FileField(
                blank=True,
                max_length=300,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="",
                verbose_name="Mobilpay Public key",
            ),
        ),
    ]
