#!/bin/sh

PORT=${PORT:-"8000"}

echo "Checking..."
python3 manage.py check

echo "Migrating databse"
python3 manage.py migrate --run-syncdb

echo "Seed"
python3 manage.py seed

echo "Start web server on $PORT"
python3 manage.py runserver "0.0.0.0:$PORT"
