# Generated by Django 3.0.4 on 2020-03-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='Phone'),
        ),
    ]
